version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
    command: flask run
